[package]
edition = "2021"
name = "ziptest_integrity"
version = "0.0.3"

[lib]
crate-type = ["cdylib", "rlib"]
name = "ziptest_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
